name: Qwik Benchmarks

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Qwik core (ensures /dist exists)
        run: pnpm build.local --qwik

      - name: Run benchmarks
        run: node scripts/benchmarks/runBenchmarks.cjs

      - name: Show benchmark output
        run: cat benchmark-results.json

      - name: Reset local changes
        run: git reset --hard

      # ✅ Do NOT clean package.json etc.

      - name: Upload benchmark results to GitHub Pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Qwik CI Benchmarks
          tool: customSmallerIsBetter
          output-file-path: benchmark-results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
